const translations = {
    es: {
        // Menú
        _tabTranslate: "Traductor",
        _tabLearn: "Aprender",
        _tabSend: "Enviar código",
        _tabAlphabet: "Abecedario",
        _tabSettings: "Ajustes",

        // Abecedario
        _alphabetTitle: "Descubre como se escribe cada letra del diccionario morse",
        _alphabetLetter: "Letra",
        _alphabetMorse: "Morse",
        _alphabetKey: "Clave",

        // Alfabeto números
        _alphabetWord0: "Cero",
        _alphabetWord1: "Uno",
        _alphabetWord2: "Dos",
        _alphabetWord3: "Tres",
        _alphabetWord4: "Cuatro",
        _alphabetWord5: "Cinco",
        _alphabetWord6: "Seis",
        _alphabetWord7: "Siete",
        _alphabetWord8: "Ocho",
        _alphabetWord9: "Nueve",

        // Alfabeto símbolos
        _alphabetSymbol1: "Punto",
        _alphabetSymbol2: "Coma",
        _alphabetSymbol3: "Interrogante",
        _alphabetSymbol4: "Comilla",
        _alphabetSymbol5: "Guión",
        _alphabetSymbol6: "Barra",
        _alphabetSymbol7: "Paréntesis izq",
        _alphabetSymbol8: "Paréntesis dcho",
        _alphabetSymbol9: "Arroba",
        _alphabetSymbol10: "Igual",

        // Traductor
        _translateTitle: "Traduce al instante cualquier texto a código morse o viceversa",
        _translateTextToMorse: "Texto a Morse",
        _translateMorseToText: "Morse a Texto",
        _translatePlaceholder1: "Escribe aquí el",
        _translatePlaceholder2: "que quieres traducir",
        _translateMorseCode: "código morse",
        _translateText: "texto",
        _translateResult1: "Aquí aparecerá tu",
        _translateResult2: "traducido",

        // Enviar código
        _sendTitle: "Utiliza estas herramientas para mandar un código morse",
        _sendMessage: "Mandar mensaje",
        _sendVibration: "Vibración",
        _sendFlashlight: "Linterna",

        // Uso de la linterna
        _flashlightTitle: "Para poder encender la linterna, debe conceder permisos",
        _flashlightPermission: "Permitir linterna",

        // Ajustes
        _dropDownSettings: "Ajustes",
        _settingsApp: "Ajustes de la aplicación",
        _settingsLang: "Idioma de la aplicación",

        // Aprender
        _learnTitle: "Desbloquea todos los níveles y aprende código morse en menos de 2 semanas",
        _learnEncouragement: "Sigue así, estás un paso más cerca de conseguirlo 💪",
        _learnCongratulations: "¡Felicidades! Has completado el nivel",
        _learnCongratulations2: "con éxito 🎉",
        _learnSuccesses: "Has acertado",
        _learnOf: "de",
        _learnRepeat: "¡Has fallado muchas! Tienes que repetir este nivel para desbloquear el siguiente",
        _learnUnlock: "Has desbloqueado el nivel",
        _learnHome: "Volver al inicio",
        _learnLevel1: "Nivel 1",
        _learnLevel2: "Nivel 2",
        _learnLevel3: "Nivel 3",
        _learnLevel4: "Nivel 4",
        _learnLevel5: "Nivel 5",
        _learnLevel6: "Nivel 6",
        _learnLevel7: "Nivel 7",
        _learnLevel8: "Nivel 8",
        _learnLevel9: "Nivel 9",
        _learnLevel10: "Nivel 10",
        _learnLevel11: "Nivel 11",
        _learnLevel12: "Nivel 12",
        _learnLevel13: "Nivel 13",
        _learnLevel14: "Nivel 14",

        // Notificaciones
        _notificationTitle: "¿Has aprendido un nuevo nivel hoy?",
        _notificationBody: "Mo pierdas el ritmo y pon aprueba lo aprendido",

        // Lista de idiomas
        _langListSpanish: "Español",
        _langListEnglish: "Inglés",
        _langListGerman: "Alemán",
        _langListFrench: "Francés",
        _langListPortuguese: "Portugués",
        _langListItalian: "Italiano",

        // Ejemplos cambiantes para las letras del alfabeto
        _alphabetWordA: "Arco",
        _alphabetWordB: "Barco",
        _alphabetWordC: "Casa",
        _alphabetWordD: "Dado",
        _alphabetWordE: "Elefante",
        _alphabetWordF: "Fuerza",
        _alphabetWordG: "Granja",
        _alphabetWordH: "Hueso",
        _alphabetWordI: "Interior",
        _alphabetWordJ: "Jungla",
        _alphabetWordK: "Koala",
        _alphabetWordL: "Luna",
        _alphabetWordM: "Mesa",
        _alphabetWordN: "Nuca",
        _alphabetWordO: "Oso",
        _alphabetWordP: "Palomitas",
        _alphabetWordQ: "Queso",
        _alphabetWordR: "Rata",
        _alphabetWordS: "Suela",
        _alphabetWordT: "Tambor",
        _alphabetWordU: "Uvas",
        _alphabetWordV: "Veneno",
        _alphabetWordW: "Whisky",
        _alphabetWordX: "Xilófono",
        _alphabetWordY: "Yuca",
        _alphabetWordZ: "Zapatos",
    },
    en: {
        // Menú
        _tabTranslate: "Translator",
        _tabLearn: "Learn",
        _tabSend: "Send code",
        _tabAlphabet: "Alphabet",
        _tabSettings: "Settings",

        // Abecedario
        _alphabetTitle: "Discover how each letter is written in the Morse dictionary",
        _alphabetLetter: "Letter",
        _alphabetMorse: "Morse",
        _alphabetKey: "Key",

        // Alfabeto números
        _alphabetWord0: "Zero",
        _alphabetWord1: "One",
        _alphabetWord2: "Two",
        _alphabetWord3: "Three",
        _alphabetWord4: "Four",
        _alphabetWord5: "Five",
        _alphabetWord6: "Six",
        _alphabetWord7: "Seven",
        _alphabetWord8: "Eight",
        _alphabetWord9: "Nine",

        // Alfabeto símbolos
        _alphabetSymbol1: "Dot",
        _alphabetSymbol2: "Comma",
        _alphabetSymbol3: "Question mark",
        _alphabetSymbol4: "Quotation mark",
        _alphabetSymbol5: "Dash",
        _alphabetSymbol6: "Slash",
        _alphabetSymbol7: "Left parenthesis",
        _alphabetSymbol8: "Right parenthesis",
        _alphabetSymbol9: "At sign",
        _alphabetSymbol10: "Equal",

        // Traductor
        _translateTitle: "Instantly translate any text to Morse code or vice versa",
        _translateTextToMorse: "Text to Morse",
        _translateMorseToText: "Morse to Text",
        _translatePlaceholder1: "Write here the",
        _translatePlaceholder2: "you want to translate",
        _translateMorseCode: "Morse code",
        _translateText: "text",
        _translateResult1: "Your",
        _translateResult2: "will appear here",

        // Enviar código
        _sendTitle: "Use these tools to send Morse code",
        _sendMessage: "Send message",
        _sendVibration: "Vibration",
        _sendFlashlight: "Flashlight",

        // Uso de la linterna
        _flashlightTitle: "To turn on the flashlight, you must grant permission",
        _flashlightPermission: "Allow flashlight",

        // Ajustes
        _dropDownSettings: "Settings",
        _settingsApp: "App settings",
        _settingsLang: "App language",

        // Aprender
        _learnTitle: "Unlock all levels and learn Morse code in less than 2 weeks",
        _learnEncouragement: "Keep going, you're one step closer to success 💪",
        _learnCongratulations: "Congratulations! You have completed the level",
        _learnCongratulations2: "successfully 🎉",
        _learnSuccesses: "You got",
        _learnOf: "out of",
        _learnRepeat: "You made too many mistakes! Repeat this level to unlock the next one",
        _learnUnlock: "You have unlocked level",
        _learnHome: "Back to home",
        _learnLevel1: "Level 1",
        _learnLevel2: "Level 2",
        _learnLevel3: "Level 3",
        _learnLevel4: "Level 4",
        _learnLevel5: "Level 5",
        _learnLevel6: "Level 6",
        _learnLevel7: "Level 7",
        _learnLevel8: "Level 8",
        _learnLevel9: "Level 9",
        _learnLevel10: "Level 10",
        _learnLevel11: "Level 11",
        _learnLevel12: "Level 12",
        _learnLevel13: "Level 13",
        _learnLevel14: "Level 14",

        // Notificaciones
        _notificationTitle: "Have you learned a new level today?",
        _notificationBody: "Don’t lose your rhythm and test what you’ve learned",

        // Lista de idiomas
        _langListSpanish: "Spanish",
        _langListEnglish: "English",
        _langListGerman: "German",
        _langListFrench: "French",
        _langListPortuguese: "Portuguese",
        _langListItalian: "Italian",

        // Ejemplos cambiantes para las letras del alfabeto
        _alphabetWordA: "Apple",
        _alphabetWordB: "Boat",
        _alphabetWordC: "Cat",
        _alphabetWordD: "Drum",
        _alphabetWordE: "Elephant",
        _alphabetWordF: "Forest",
        _alphabetWordG: "Garden",
        _alphabetWordH: "House",
        _alphabetWordI: "Island",
        _alphabetWordJ: "Jungle",
        _alphabetWordK: "Kite",
        _alphabetWordL: "Lamp",
        _alphabetWordM: "Mountain",
        _alphabetWordN: "Nest",
        _alphabetWordO: "Ocean",
        _alphabetWordP: "Pumpkin",
        _alphabetWordQ: "Queen",
        _alphabetWordR: "River",
        _alphabetWordS: "Sun",
        _alphabetWordT: "Tree",
        _alphabetWordU: "Umbrella",
        _alphabetWordV: "Valley",
        _alphabetWordW: "Whale",
        _alphabetWordX: "Xylophone",
        _alphabetWordY: "Yard",
        _alphabetWordZ: "Zoo"
    },
    de: {
        // Menú
        _tabTranslate: "Übersetzer",
        _tabLearn: "Lernen",
        _tabSend: "Code senden",
        _tabAlphabet: "Alphabet",
        _tabSettings: "Einstellungen",

        // Abecedario
        _alphabetTitle: "Entdecke, wie jeder Buchstabe im Morsewörterbuch geschrieben wird",
        _alphabetLetter: "Buchstabe",
        _alphabetMorse: "Morse",
        _alphabetKey: "Schlüssel",

        // Alfabeto números
        _alphabetWord0: "Null",
        _alphabetWord1: "Eins",
        _alphabetWord2: "Zwei",
        _alphabetWord3: "Drei",
        _alphabetWord4: "Vier",
        _alphabetWord5: "Fünf",
        _alphabetWord6: "Sechs",
        _alphabetWord7: "Sieben",
        _alphabetWord8: "Acht",
        _alphabetWord9: "Neun",

        // Alfabeto símbolos
        _alphabetSymbol1: "Punkt",
        _alphabetSymbol2: "Komma",
        _alphabetSymbol3: "Fragezeichen",
        _alphabetSymbol4: "Anführungszeichen",
        _alphabetSymbol5: "Bindestrich",
        _alphabetSymbol6: "Schrägstrich",
        _alphabetSymbol7: "Linke Klammer",
        _alphabetSymbol8: "Rechte Klammer",
        _alphabetSymbol9: "At-Zeichen",
        _alphabetSymbol10: "Gleich",

        // Traductor
        _translateTitle: "Übersetze sofort jeden Text in Morsecode oder umgekehrt",
        _translateTextToMorse: "Text zu Morse",
        _translateMorseToText: "Morse zu Text",
        _translatePlaceholder1: "Schreibe hier den",
        _translatePlaceholder2: "den du übersetzen möchtest",
        _translateMorseCode: "Morsecode",
        _translateText: "Text",
        _translateResult1: "Hier erscheint dein",
        _translateResult2: "übersetzter Text",

        // Enviar código
        _sendTitle: "Verwende diese Werkzeuge, um einen Morsecode zu senden",
        _sendMessage: "Nachricht senden",
        _sendVibration: "Vibration",
        _sendFlashlight: "Taschenlampe",

        // Uso de la linterna
        _flashlightTitle: "Um die Taschenlampe einzuschalten, müssen Sie die Berechtigung erteilen",
        _flashlightPermission: "Taschenlampe erlauben",

        // Ajustes
        _dropDownSettings: "Einstellungen",
        _settingsApp: "App-Einstellungen",
        _settingsLang: "App-Sprache",

        // Aprender
        _learnTitle: "Schalte alle Level frei und lerne Morsecode in weniger als 2 Wochen",
        _learnEncouragement: "Mach weiter so, du bist dem Ziel ein Stück näher 💪",
        _learnCongratulations: "Glückwunsch! Du hast das Level abgeschlossen",
        _learnCongratulations2: "erfolgreich 🎉",
        _learnSuccesses: "Du hast",
        _learnOf: "von",
        _learnRepeat: "Du hast viele Fehler gemacht! Wiederhole dieses Level, um das nächste freizuschalten",
        _learnUnlock: "Du hast Level freigeschaltet",
        _learnHome: "Zurück zum Start",
        _learnLevel1: "Level 1",
        _learnLevel2: "Level 2",
        _learnLevel3: "Level 3",
        _learnLevel4: "Level 4",
        _learnLevel5: "Level 5",
        _learnLevel6: "Level 6",
        _learnLevel7: "Level 7",
        _learnLevel8: "Level 8",
        _learnLevel9: "Level 9",
        _learnLevel10: "Level 10",
        _learnLevel11: "Level 11",
        _learnLevel12: "Level 12",
        _learnLevel13: "Level 13",
        _learnLevel14: "Level 14",

        // Notificaciones
        _notificationTitle: "Hast du heute ein neues Level gelernt?",
        _notificationBody: "Verliere nicht den Rhythmus und teste, was du gelernt hast",

        // Lista de idiomas
        _langListSpanish: "Spanisch",
        _langListEnglish: "Englisch",
        _langListGerman: "Deutsch",
        _langListFrench: "Französisch",
        _langListPortuguese: "Portugiesisch",
        _langListItalian: "Italienisch",

        // Ejemplos cambiantes para las letras del alfabeto
        _alphabetWordA: "Apfel",
        _alphabetWordB: "Ball",
        _alphabetWordC: "Clown",
        _alphabetWordD: "Dorf",
        _alphabetWordE: "Eule",
        _alphabetWordF: "Fisch",
        _alphabetWordG: "Garten",
        _alphabetWordH: "Himmel",
        _alphabetWordI: "Insel",
        _alphabetWordJ: "Junge",
        _alphabetWordK: "Kuh",
        _alphabetWordL: "Lampe",
        _alphabetWordM: "Mond",
        _alphabetWordN: "Nadel",
        _alphabetWordO: "Ofen",
        _alphabetWordP: "Pferd",
        _alphabetWordQ: "Quelle",
        _alphabetWordR: "Rose",
        _alphabetWordS: "Sonne",
        _alphabetWordT: "Turm",
        _alphabetWordU: "Uhr",
        _alphabetWordV: "Vogel",
        _alphabetWordW: "Wald",
        _alphabetWordX: "Xylophon",
        _alphabetWordY: "Yacht",
        _alphabetWordZ: "Zebra",
    },
    fr: {
        // Menú
        _tabTranslate: "Traducteur",
        _tabLearn: "Apprendre",
        _tabSend: "Envoyer le code",
        _tabAlphabet: "Alphabet",
        _tabSettings: "Paramètres",

        // Abecedario
        _alphabetTitle: "Découvrez comment chaque lettre s’écrit dans le dictionnaire Morse",
        _alphabetLetter: "Lettre",
        _alphabetMorse: "Morse",
        _alphabetKey: "Clé",

        // Alfabeto números
        _alphabetWord0: "Zéro",
        _alphabetWord1: "Un",
        _alphabetWord2: "Deux",
        _alphabetWord3: "Trois",
        _alphabetWord4: "Quatre",
        _alphabetWord5: "Cinq",
        _alphabetWord6: "Six",
        _alphabetWord7: "Sept",
        _alphabetWord8: "Huit",
        _alphabetWord9: "Neuf",

        // Alfabeto símbolos
        _alphabetSymbol1: "Point",
        _alphabetSymbol2: "Virgule",
        _alphabetSymbol3: "Point d’interrogation",
        _alphabetSymbol4: "Guillemet",
        _alphabetSymbol5: "Tiret",
        _alphabetSymbol6: "Barre oblique",
        _alphabetSymbol7: "Parenthèse gauche",
        _alphabetSymbol8: "Parenthèse droite",
        _alphabetSymbol9: "Arobase",
        _alphabetSymbol10: "Égal",

        // Traductor
        _translateTitle: "Traduisez instantanément n’importe quel texte en code Morse ou inversement",
        _translateTextToMorse: "Texte vers Morse",
        _translateMorseToText: "Morse vers texte",
        _translatePlaceholder1: "Écrivez ici le",
        _translatePlaceholder2: "que vous souhaitez traduire",
        _translateMorseCode: "code Morse",
        _translateText: "texte",
        _translateResult1: "Votre",
        _translateResult2: "apparaîtra ici",

        // Enviar código
        _sendTitle: "Utilisez ces outils pour envoyer un code Morse",
        _sendMessage: "Envoyer un message",
        _sendVibration: "Vibration",
        _sendFlashlight: "Lampe de poche",

        // Uso de la linterna
        _flashlightTitle: "Pour allumer la lampe, vous devez accorder les permissions",
        _flashlightPermission: "Autoriser la lampe",

        // Ajustes
        _dropDownSettings: "Paramètres",
        _settingsApp: "Paramètres de l’application",
        _settingsLang: "Langue de l’application",

        // Aprender
        _learnTitle: "Débloquez tous les niveaux et apprenez le code Morse en moins de 2 semaines",
        _learnEncouragement: "Continuez, vous êtes tout près du but 💪",
        _learnCongratulations: "Félicitations ! Vous avez terminé le niveau",
        _learnCongratulations2: "avec succès 🎉",
        _learnSuccesses: "Vous avez réussi",
        _learnOf: "sur",
        _learnRepeat: "Vous avez fait trop d’erreurs ! Répétez ce niveau pour débloquer le suivant",
        _learnUnlock: "Vous avez débloqué le niveau",
        _learnHome: "Retour à l’accueil",
        _learnLevel1: "Niveau 1",
        _learnLevel2: "Niveau 2",
        _learnLevel3: "Niveau 3",
        _learnLevel4: "Niveau 4",
        _learnLevel5: "Niveau 5",
        _learnLevel6: "Niveau 6",
        _learnLevel7: "Niveau 7",
        _learnLevel8: "Niveau 8",
        _learnLevel9: "Niveau 9",
        _learnLevel10: "Niveau 10",
        _learnLevel11: "Niveau 11",
        _learnLevel12: "Niveau 12",
        _learnLevel13: "Niveau 13",
        _learnLevel14: "Niveau 14",

        // Notificaciones
        _notificationTitle: "Avez-vous appris un nouveau niveau aujourd’hui ?",
        _notificationBody: "Ne perdez pas le rythme et testez ce que vous avez appris",

        // Lista de idiomas
        _langListSpanish: "Espagnol",
        _langListEnglish: "Anglais",
        _langListArabic: "Arabe",
        _langListGerman: "Allemand",
        _langListFrench: "Français",
        _langListHindi: "Hindi",
        _langListIndonesian: "Indonésien",
        _langListPortuguese: "Portugais",
        _langListRussian: "Russe",
        _langListPolish: "Polonais",
        _langListVietnamese: "Vietnamien",
        _langListTurkish: "Turc",
        _langListItalian: "Italien",
        _langListFarsi: "Farsi",

        // Ejemplos cambiantes para las letras del alfabeto
        _alphabetWordA: "Arbre",
        _alphabetWordB: "Bateau",
        _alphabetWordC: "Chien",
        _alphabetWordD: "Drapeau",
        _alphabetWordE: "Étoile",
        _alphabetWordF: "Forêt",
        _alphabetWordG: "Gâteau",
        _alphabetWordH: "Hirondelle",
        _alphabetWordI: "Île",
        _alphabetWordJ: "Jardin",
        _alphabetWordK: "Koala",
        _alphabetWordL: "Lune",
        _alphabetWordM: "Montagne",
        _alphabetWordN: "Nuage",
        _alphabetWordO: "Océan",
        _alphabetWordP: "Papillon",
        _alphabetWordQ: "Quiche",
        _alphabetWordR: "Rivière",
        _alphabetWordS: "Soleil",
        _alphabetWordT: "Table",
        _alphabetWordU: "Uniforme",
        _alphabetWordV: "Voiture",
        _alphabetWordW: "Wagon",
        _alphabetWordX: "Xylophone",
        _alphabetWordY: "Yaourt",
        _alphabetWordZ: "Zèbre",
    },
    pt: {
        // Menú
        _tabTranslate: "Tradutor",
        _tabLearn: "Aprender",
        _tabSend: "Enviar código",
        _tabAlphabet: "Alfabeto",
        _tabSettings: "Configurações",

        // Abecedario
        _alphabetTitle: "Descubra como se escreve cada letra do dicionário Morse",
        _alphabetLetter: "Letra",
        _alphabetMorse: "Morse",
        _alphabetKey: "Chave",

        // Alfabeto números
        _alphabetWord0: "Zero",
        _alphabetWord1: "Um",
        _alphabetWord2: "Dois",
        _alphabetWord3: "Três",
        _alphabetWord4: "Quatro",
        _alphabetWord5: "Cinco",
        _alphabetWord6: "Seis",
        _alphabetWord7: "Sete",
        _alphabetWord8: "Oito",
        _alphabetWord9: "Nove",

        // Alfabeto símbolos
        _alphabetSymbol1: "Ponto",
        _alphabetSymbol2: "Vírgula",
        _alphabetSymbol3: "Interrogação",
        _alphabetSymbol4: "Aspa",
        _alphabetSymbol5: "Hífen",
        _alphabetSymbol6: "Barra",
        _alphabetSymbol7: "Parêntese esq.",
        _alphabetSymbol8: "Parêntese dir.",
        _alphabetSymbol9: "Arroba",
        _alphabetSymbol10: "Igual",

        // Traductor
        _translateTitle: "Traduza instantaneamente qualquer texto para código Morse ou vice-versa",
        _translateTextToMorse: "Texto para Morse",
        _translateMorseToText: "Morse para Texto",
        _translatePlaceholder1: "Escreva aqui o",
        _translatePlaceholder2: "que deseja traduzir",
        _translateMorseCode: "código Morse",
        _translateText: "texto",
        _translateResult1: "Aqui aparecerá o seu",
        _translateResult2: "traduzido",

        // Enviar código
        _sendTitle: "Use estas ferramentas para enviar um código Morse",
        _sendMessage: "Enviar mensagem",
        _sendVibration: "Vibração",
        _sendFlashlight: "Lanterna",

        // Uso de la linterna
        _flashlightTitle: "Para ligar a lanterna, deve conceder permissões",
        _flashlightPermission: "Permitir lanterna",

        // Ajustes
        _dropDownSettings: "Configurações",
        _settingsApp: "Configurações do aplicativo",
        _settingsLang: "Idioma do aplicativo",

        // Aprender
        _learnTitle: "Desbloqueie todos os níveis e aprenda código Morse em menos de 2 semanas",
        _learnEncouragement: "Continue assim, está a um passo de conseguir 💪",
        _learnCongratulations: "Parabéns! Concluiu o nível",
        _learnCongratulations2: "com sucesso 🎉",
        _learnSuccesses: "Acertou",
        _learnOf: "de",
        _learnRepeat: "Errou muitas! Deve repetir este nível para desbloquear o próximo",
        _learnUnlock: "Desbloqueou o nível",
        _learnHome: "Voltar ao início",
        _learnLevel1: "Nível 1",
        _learnLevel2: "Nível 2",
        _learnLevel3: "Nível 3",
        _learnLevel4: "Nível 4",
        _learnLevel5: "Nível 5",
        _learnLevel6: "Nível 6",
        _learnLevel7: "Nível 7",
        _learnLevel8: "Nível 8",
        _learnLevel9: "Nível 9",
        _learnLevel10: "Nível 10",
        _learnLevel11: "Nível 11",
        _learnLevel12: "Nível 12",
        _learnLevel13: "Nível 13",
        _learnLevel14: "Nível 14",

        // Notificações
        _notificationTitle: "Aprendeu um novo nível hoje?",
        _notificationBody: "Não perca o ritmo e teste o que aprendeu",

        // Lista de idiomas
        _langListSpanish: "Espanhol",
        _langListEnglish: "Inglês",
        _langListGerman: "Alemão",
        _langListFrench: "Francês",
        _langListPortuguese: "Português",
        _langListItalian: "Italiano",

        // Exemplos aleatórios para as letras do alfabeto
        _alphabetWordA: "Abacate",
        _alphabetWordB: "Bola",
        _alphabetWordC: "Cachorro",
        _alphabetWordD: "Dente",
        _alphabetWordE: "Estrela",
        _alphabetWordF: "Faca",
        _alphabetWordG: "Gato",
        _alphabetWordH: "Hotel",
        _alphabetWordI: "Ilha",
        _alphabetWordJ: "Janela",
        _alphabetWordK: "Karaté",
        _alphabetWordL: "Laranja",
        _alphabetWordM: "Mochila",
        _alphabetWordN: "Navio",
        _alphabetWordO: "Olho",
        _alphabetWordP: "Pato",
        _alphabetWordQ: "Queijo",
        _alphabetWordR: "Rosa",
        _alphabetWordS: "Sol",
        _alphabetWordT: "Tigre",
        _alphabetWordU: "Uva",
        _alphabetWordV: "Vento",
        _alphabetWordW: "Whisky",
        _alphabetWordX: "Xadrez",
        _alphabetWordY: "Yoga",
        _alphabetWordZ: "Zebra",
    },
    it: {
        // Menú
        _tabTranslate: "Traduttore",
        _tabLearn: "Impara",
        _tabSend: "Invia codice",
        _tabAlphabet: "Alfabeto",
        _tabSettings: "Impostazioni",

        // Abecedario
        _alphabetTitle: "Scopri come si scrive ogni lettera del dizionario Morse",
        _alphabetLetter: "Lettera",
        _alphabetMorse: "Morse",
        _alphabetKey: "Chiave",

        // Alfabeto numeri
        _alphabetWord0: "Zero",
        _alphabetWord1: "Uno",
        _alphabetWord2: "Due",
        _alphabetWord3: "Tre",
        _alphabetWord4: "Quattro",
        _alphabetWord5: "Cinque",
        _alphabetWord6: "Sei",
        _alphabetWord7: "Sette",
        _alphabetWord8: "Otto",
        _alphabetWord9: "Nove",

        // Alfabeto simboli
        _alphabetSymbol1: "Punto",
        _alphabetSymbol2: "Virgola",
        _alphabetSymbol3: "Domanda",
        _alphabetSymbol4: "Virgolette",
        _alphabetSymbol5: "Trattino",
        _alphabetSymbol6: "Barra",
        _alphabetSymbol7: "Parentesi sin.",
        _alphabetSymbol8: "Parentesi des.",
        _alphabetSymbol9: "Chiocciola",
        _alphabetSymbol10: "Uguale",

        // Traduttore
        _translateTitle: "Traduci istantaneamente qualsiasi testo in codice Morse o viceversa",
        _translateTextToMorse: "Testo in Morse",
        _translateMorseToText: "Morse in Testo",
        _translatePlaceholder1: "Scrivi qui il",
        _translatePlaceholder2: "che vuoi tradurre",
        _translateMorseCode: "codice Morse",
        _translateText: "testo",
        _translateResult1: "Qui apparirà il tuo",
        _translateResult2: "tradotto",

        // Invia codice
        _sendTitle: "Usa questi strumenti per inviare un codice Morse",
        _sendMessage: "Invia messaggio",
        _sendVibration: "Vibrazione",
        _sendFlashlight: "Torcia",

        // Uso della torcia
        _flashlightTitle: "Per accendere la torcia, devi concedere i permessi",
        _flashlightPermission: "Permetti torcia",

        // Impostazioni
        _dropDownSettings: "Impostazioni",
        _settingsApp: "Impostazioni dell'applicazione",
        _settingsLang: "Lingua dell'applicazione",

        // Impara
        _learnTitle: "Sblocca tutti i livelli e impara il codice Morse in meno di 2 settimane",
        _learnEncouragement: "Continua così, sei a un passo dal riuscirci 💪",
        _learnCongratulations: "Congratulazioni! Hai completato il livello",
        _learnCongratulations2: "con successo 🎉",
        _learnSuccesses: "Hai indovinato",
        _learnOf: "di",
        _learnRepeat: "Hai sbagliato troppo! Devi ripetere questo livello per sbloccare il successivo",
        _learnUnlock: "Hai sbloccato il livello",
        _learnHome: "Torna all'inizio",
        _learnLevel1: "Livello 1",
        _learnLevel2: "Livello 2",
        _learnLevel3: "Livello 3",
        _learnLevel4: "Livello 4",
        _learnLevel5: "Livello 5",
        _learnLevel6: "Livello 6",
        _learnLevel7: "Livello 7",
        _learnLevel8: "Livello 8",
        _learnLevel9: "Livello 9",
        _learnLevel10: "Livello 10",
        _learnLevel11: "Livello 11",
        _learnLevel12: "Livello 12",
        _learnLevel13: "Livello 13",
        _learnLevel14: "Livello 14",

        // Notifiche
        _notificationTitle: "Hai imparato un nuovo livello oggi?",
        _notificationBody: "Non perdere il ritmo e metti alla prova ciò che hai imparato",

        // Elenco lingue
        _langListSpanish: "Spagnolo",
        _langListEnglish: "Inglese",
        _langListGerman: "Tedesco",
        _langListFrench: "Francese",
        _langListPortuguese: "Portoghese",
        _langListItalian: "Italiano",

        // Esempi casuali per le lettere dell'alfabeto
        _alphabetWordA: "Aquila",
        _alphabetWordB: "Barca",
        _alphabetWordC: "Cuore",
        _alphabetWordD: "Dente",
        _alphabetWordE: "Erba",
        _alphabetWordF: "Fiume",
        _alphabetWordG: "Gioco",
        _alphabetWordH: "Hotel",
        _alphabetWordI: "Isola",
        _alphabetWordJ: "Juventus",
        _alphabetWordK: "Ketchup",
        _alphabetWordL: "Luna",
        _alphabetWordM: "Mela",
        _alphabetWordN: "Nave",
        _alphabetWordO: "Orso",
        _alphabetWordP: "Pane",
        _alphabetWordQ: "Quadro",
        _alphabetWordR: "Rana",
        _alphabetWordS: "Sale",
        _alphabetWordT: "Tavolo",
        _alphabetWordU: "Uva",
        _alphabetWordV: "Vento",
        _alphabetWordW: "Whisky",
        _alphabetWordX: "Xilofono",
        _alphabetWordY: "Yogurt",
        _alphabetWordZ: "Zaino",
    }
}

export { translations };